controller_list:
  - name: r2/l_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/left_arm/joint0
      - r2/left_arm/joint1
      - r2/left_arm/joint2
      - r2/left_arm/joint3
      - r2/left_arm/joint4
      - r2/left_arm/joint5
      - r2/left_arm/joint6
  - name: r2/r_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/right_arm/joint0
      - r2/right_arm/joint1
      - r2/right_arm/joint2
      - r2/right_arm/joint3
      - r2/right_arm/joint4
      - r2/right_arm/joint5
      - r2/right_arm/joint6
  - name: r2/l_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - r2/left_arm/hand/index/joint0
      - r2/left_arm/hand/index/joint1
      - r2/left_arm/hand/index/joint2
      - r2/left_arm/hand/index/joint3
      - r2/left_arm/hand/middle/joint0
      - r2/left_arm/hand/middle/joint1
      - r2/left_arm/hand/middle/joint2
      - r2/left_arm/hand/middle/joint3
      - r2/left_arm/hand/little/joint0
      - r2/left_arm/hand/little/joint1
      - r2/left_arm/hand/little/joint2
      - r2/left_arm/hand/ring/joint0
      - r2/left_arm/hand/ring/joint1
      - r2/left_arm/hand/ring/joint2
      - r2/left_arm/hand/thumb/joint0
      - r2/left_arm/hand/thumb/joint1
      - r2/left_arm/hand/thumb/joint2
      - r2/left_arm/hand/thumb/joint3
  - name: r2/r_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - r2/right_arm/hand/index/joint0
      - r2/right_arm/hand/index/joint1
      - r2/right_arm/hand/index/joint2
      - r2/right_arm/hand/index/joint3
      - r2/right_arm/hand/middle/joint0
      - r2/right_arm/hand/middle/joint1
      - r2/right_arm/hand/middle/joint2
      - r2/right_arm/hand/middle/joint3
      - r2/right_arm/hand/little/joint0
      - r2/right_arm/hand/little/joint1
      - r2/right_arm/hand/little/joint2
      - r2/right_arm/hand/ring/joint0
      - r2/right_arm/hand/ring/joint1
      - r2/right_arm/hand/ring/joint2
      - r2/right_arm/hand/thumb/joint0
      - r2/right_arm/hand/thumb/joint1
      - r2/right_arm/hand/thumb/joint2
      - r2/right_arm/hand/thumb/joint3
  - name: r2/neck_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/neck/joint0
      - r2/neck/joint1
      - r2/neck/joint2
  - name: r2/waist_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/waist/joint0