r2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  r_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/right_arm/joint0
      - r2/right_arm/joint1
      - r2/right_arm/joint2
      - r2/right_arm/joint3
      - r2/right_arm/joint4
      - r2/right_arm/joint5
      - r2/right_arm/joint6
    gains:
      r2/right_arm/joint0: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/joint1: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/joint2: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/joint3: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/joint4: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/joint5: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/joint6: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
    follow_joint_trajectory:
      joints:
        - r2/right_arm/joint0
        - r2/right_arm/joint1
        - r2/right_arm/joint2
        - r2/right_arm/joint3
        - r2/right_arm/joint4
        - r2/right_arm/joint5
        - r2/right_arm/joint6
      constraints:
        goal_time: 10.0
        r2/right_arm/joint0:
          goal: 0.2
        r2/right_arm/joint1:
          goal: 0.2
        r2/right_arm/joint2:
          goal: 0.2
        r2/right_arm/joint3:
          goal: 0.2
        r2/right_arm/joint4:
          goal: 0.2
        r2/right_arm/joint5:
          goal: 0.2
        r2/right_arm/joint6:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default


  l_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/left_arm/joint0
      - r2/left_arm/joint1
      - r2/left_arm/joint2
      - r2/left_arm/joint3
      - r2/left_arm/joint4
      - r2/left_arm/joint5
      - r2/left_arm/joint6
    gains:
      r2/left_arm/joint0: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/joint1: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/joint2: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/joint3: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/joint4: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/joint5: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/joint6: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
    follow_joint_trajectory:
      joints:
        - r2/left_arm/joint0
        - r2/left_arm/joint1
        - r2/left_arm/joint2
        - r2/left_arm/joint3
        - r2/left_arm/joint4
        - r2/left_arm/joint5
        - r2/left_arm/joint6
      constraints:
        goal_time: 10.0
        r2/left_arm/joint0:
          goal: 0.2
        r2/left_arm/joint1:
          goal: 0.2
        r2/left_arm/joint2:
          goal: 0.2
        r2/left_arm/joint3:
          goal: 0.2
        r2/left_arm/joint4:
          goal: 0.2
        r2/left_arm/joint5:
          goal: 0.2
        r2/left_arm/joint6:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

  waist_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - r2/waist/joint0
    gains:
      r2/waist/joint0: {p: 1000.0, d: 700, i: 100, i_clamp: 500.0}
    follow_joint_trajectory_node:
      joints:
        - r2/waist/joint0
      constraints:
        goal_time: 5.0
        r2/waist/joint0:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

  neck_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/neck/joint0
      - r2/neck/joint1
      - r2/neck/joint2
    gains:
      r2/neck/joint0: {p: 50.0, d: 15, i: 2, i_clamp: 4.0}
      r2/neck/joint1: {p: 20.0, d:  4, i: 2, i_clamp: 4.0}
      r2/neck/joint2: {p: 20.0, d:  4, i: 2, i_clamp: 4.0}
    follow_joint_trajectory_node:
      joints:
        - r2/neck/joint0
        - r2/neck/joint1
        - r2/neck/joint2
      constraints:
        goal_time: 5.0
        r2/neck/joint0:
          goal: 0.2
        r2/neck/joint1:
          goal: 0.2
        r2/neck/joint2:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default


  l_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/left_arm/hand/index/joint0
      - r2/left_arm/hand/index/joint1
      - r2/left_arm/hand/index/joint2
      - r2/left_arm/hand/index/joint3
      - r2/left_arm/hand/little/joint0
      - r2/left_arm/hand/little/joint1
      - r2/left_arm/hand/little/joint2
      - r2/left_arm/hand/middle/joint0
      - r2/left_arm/hand/middle/joint1
      - r2/left_arm/hand/middle/joint2
      - r2/left_arm/hand/middle/joint3
      - r2/left_arm/hand/ring/joint0
      - r2/left_arm/hand/ring/joint1
      - r2/left_arm/hand/ring/joint2
      - r2/left_arm/hand/thumb/joint0
      - r2/left_arm/hand/thumb/joint1
      - r2/left_arm/hand/thumb/joint2
      - r2/left_arm/hand/thumb/joint3
    gains:
      r2/left_arm/hand/index/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/index/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/index/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/index/joint3: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/little/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/little/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/little/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/middle/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/middle/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/middle/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/middle/joint3: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/ring/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/ring/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/ring/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/thumb/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/thumb/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/thumb/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/thumb/joint3: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
    follow_joint_trajectory_node:
      joints:
        - r2/left_arm/hand/index/joint0
        - r2/left_arm/hand/index/joint1
        - r2/left_arm/hand/index/joint2
        - r2/left_arm/hand/index/joint3
        - r2/left_arm/hand/little/joint0
        - r2/left_arm/hand/little/joint1
        - r2/left_arm/hand/little/joint2
        - r2/left_arm/hand/middle/joint0
        - r2/left_arm/hand/middle/joint1
        - r2/left_arm/hand/middle/joint2
        - r2/left_arm/hand/middle/joint3
        - r2/left_arm/hand/ring/joint0
        - r2/left_arm/hand/ring/joint1
        - r2/left_arm/hand/ring/joint2
        - r2/left_arm/hand/thumb/joint0
        - r2/left_arm/hand/thumb/joint1
        - r2/left_arm/hand/thumb/joint2
        - r2/left_arm/hand/thumb/joint3
      constraints:
        goal_time: 2.0
        r2/left_arm/hand/index/joint0:
          goal: 0.2
        r2/left_arm/hand/index/joint1:
          goal: 0.2
        r2/left_arm/hand/index/joint2:
          goal: 0.2
        r2/left_arm/hand/index/joint3:
          goal: 0.2
        r2/left_arm/hand/little/joint0:
          goal: 0.2
        r2/left_arm/hand/little/joint1:
          goal: 0.2
        r2/left_arm/hand/little/joint2:
          goal: 0.2
        r2/left_arm/hand/middle/joint0:
          goal: 0.2
        r2/left_arm/hand/middle/joint1:
          goal: 0.2
        r2/left_arm/hand/middle/joint2:
          goal: 0.2
        r2/left_arm/hand/middle/joint3:
          goal: 0.2
        r2/left_arm/hand/ring/joint0:
          goal: 0.2
        r2/left_arm/hand/ring/joint1:
          goal: 0.2
        r2/left_arm/hand/ring/joint2:
          goal: 0.2
        r2/left_arm/hand/thumb/joint0:
          goal: 0.2
        r2/left_arm/hand/thumb/joint1:
          goal: 0.2
        r2/left_arm/hand/thumb/joint2:
          goal: 0.2
        r2/left_arm/hand/thumb/joint3:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default


  r_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/right_arm/hand/index/joint0
      - r2/right_arm/hand/index/joint1
      - r2/right_arm/hand/index/joint2
      - r2/right_arm/hand/index/joint3
      - r2/right_arm/hand/little/joint0
      - r2/right_arm/hand/little/joint1
      - r2/right_arm/hand/little/joint2
      - r2/right_arm/hand/middle/joint0
      - r2/right_arm/hand/middle/joint1
      - r2/right_arm/hand/middle/joint2
      - r2/right_arm/hand/middle/joint3
      - r2/right_arm/hand/ring/joint0
      - r2/right_arm/hand/ring/joint1
      - r2/right_arm/hand/ring/joint2
      - r2/right_arm/hand/thumb/joint0
      - r2/right_arm/hand/thumb/joint1
      - r2/right_arm/hand/thumb/joint2
      - r2/right_arm/hand/thumb/joint3
    gains:
      r2/right_arm/hand/index/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/index/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/index/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/index/joint3: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/little/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/little/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/little/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/middle/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/middle/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/middle/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/middle/joint3: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/ring/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/ring/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/ring/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/thumb/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/thumb/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/thumb/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/thumb/joint3: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
    follow_joint_trajectory_node:
      joints:
        - r2/right_arm/hand/index/joint0
        - r2/right_arm/hand/index/joint1
        - r2/right_arm/hand/index/joint2
        - r2/right_arm/hand/index/joint3
        - r2/right_arm/hand/little/joint0
        - r2/right_arm/hand/little/joint1
        - r2/right_arm/hand/little/joint2
        - r2/right_arm/hand/middle/joint0
        - r2/right_arm/hand/middle/joint1
        - r2/right_arm/hand/middle/joint2
        - r2/right_arm/hand/middle/joint3
        - r2/right_arm/hand/ring/joint0
        - r2/right_arm/hand/ring/joint1
        - r2/right_arm/hand/ring/joint2
        - r2/right_arm/hand/thumb/joint0
        - r2/right_arm/hand/thumb/joint1
        - r2/right_arm/hand/thumb/joint2
        - r2/right_arm/hand/thumb/joint3
      constraints:
        goal_time: 2.0
        r2/right_arm/hand/index/joint0:
          goal: 0.2
        r2/right_arm/hand/index/joint1:
          goal: 0.2
        r2/right_arm/hand/index/joint2:
          goal: 0.2
        r2/right_arm/hand/index/joint3:
          goal: 0.2
        r2/right_arm/hand/little/joint0:
          goal: 0.2
        r2/right_arm/hand/little/joint1:
          goal: 0.2
        r2/right_arm/hand/little/joint2:
          goal: 0.2
        r2/right_arm/hand/middle/joint0:
          goal: 0.2
        r2/right_arm/hand/middle/joint1:
          goal: 0.2
        r2/right_arm/hand/middle/joint2:
          goal: 0.2
        r2/right_arm/hand/middle/joint3:
          goal: 0.2
        r2/right_arm/hand/ring/joint0:
          goal: 0.2
        r2/right_arm/hand/ring/joint1:
          goal: 0.2
        r2/right_arm/hand/ring/joint2:
          goal: 0.2
        r2/right_arm/hand/thumb/joint0:
          goal: 0.2
        r2/right_arm/hand/thumb/joint1:
          goal: 0.2
        r2/right_arm/hand/thumb/joint2:
          goal: 0.2
        r2/right_arm/hand/thumb/joint3:
          goal: 0.2

      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

  r_leg_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/right_leg/joint0
      - r2/right_leg/joint1
      - r2/right_leg/joint2
      - r2/right_leg/joint3
      - r2/right_leg/joint4
      - r2/right_leg/joint5
      - r2/right_leg/joint6
    gains:
      r2/right_leg/joint0: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/right_leg/joint1: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/right_leg/joint2: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/right_leg/joint3: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/right_leg/joint4: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/right_leg/joint5: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/right_leg/joint6: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
    follow_joint_trajectory:
      joints:
        - r2/right_leg/joint0
        - r2/right_leg/joint1
        - r2/right_leg/joint2
        - r2/right_leg/joint3
        - r2/right_leg/joint4
        - r2/right_leg/joint5
        - r2/right_leg/joint6
      constraints:
        goal_time: 10.0
        r2/right_leg/joint0:
          goal: 0.2
        r2/right_leg/joint1:
          goal: 0.2
        r2/right_leg/joint2:
          goal: 0.2
        r2/right_leg/joint3:
          goal: 0.2
        r2/right_leg/joint4:
          goal: 0.2
        r2/right_leg/joint5:
          goal: 0.2
        r2/right_leg/joint6:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

  l_leg_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/left_leg/joint0
      - r2/left_leg/joint1
      - r2/left_leg/joint2
      - r2/left_leg/joint3
      - r2/left_leg/joint4
      - r2/left_leg/joint5
      - r2/left_leg/joint6
    gains:
      r2/left_leg/joint0: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/left_leg/joint1: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/left_leg/joint2: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/left_leg/joint3: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/left_leg/joint4: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/left_leg/joint5: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
      r2/left_leg/joint6: {p: 2000.0, d: 150, i: 10, i_clamp: 100.0}
    follow_joint_trajectory:
      joints:
        - r2/left_leg/joint0
        - r2/left_leg/joint1
        - r2/left_leg/joint2
        - r2/left_leg/joint3
        - r2/left_leg/joint4
        - r2/left_leg/joint5
        - r2/left_leg/joint6
      constraints:
        goal_time: 10.0
        r2/left_leg/joint0:
          goal: 0.2
        r2/left_leg/joint1:
          goal: 0.2
        r2/left_leg/joint2:
          goal: 0.2
        r2/left_leg/joint3:
          goal: 0.2
        r2/left_leg/joint4:
          goal: 0.2
        r2/left_leg/joint5:
          goal: 0.2
        r2/left_leg/joint6:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default


  l_foot_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/left_leg/gripper/joint0
      - r2/left_leg/gripper/joint1
      - r2/left_leg/gripper/joint2
    gains:
      r2/left_leg/gripper/joint0: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_leg/gripper/joint1: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_leg/gripper/joint2: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
    follow_joint_trajectory:
      joints:
        - r2/left_leg/gripper/joint0
        - r2/left_leg/gripper/joint1
        - r2/left_leg/gripper/joint2
      constraints:
        goal_time: 10.0
        r2/left_leg/gripper/joint0:
          goal: 0.2
        r2/left_leg/gripper/joint1:
          goal: 0.2
        r2/left_leg/gripper/joint2:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default


  r_foot_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/right_leg/gripper/joint0
      - r2/right_leg/gripper/joint1
      - r2/right_leg/gripper/joint2
    gains:
      r2/right_leg/gripper/joint0: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_leg/gripper/joint1: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_leg/gripper/joint2: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
    follow_joint_trajectory:
      joints:
        - r2/right_leg/gripper/joint0
        - r2/right_leg/gripper/joint1
        - r2/right_leg/gripper/joint2
      constraints:
        goal_time: 10.0
        r2/right_leg/gripper/joint0:
          goal: 0.2
        r2/right_leg/gripper/joint1:
          goal: 0.2
        r2/right_leg/gripper/joint2:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

